### ISSUE TITLE
Atividade #5 - Exploração de dados

### ISSUE THREAD

**Issue by JuSReis** [annaneto/avanti-bootcamp-cdd#2]
Criar o notebook com as seções: Descrição dos dados (quantidade de instâncias, variáveis, tipos e valores faltantes), Perguntas de partida e hipóteses (informações e suposições possíveis dos dados), e Insights (respostas e informações relevantes obtidas).

**Comment by JuSReis** [comment]
Aeee muito bom!!

**Comment by fiuzatayna** [comment]
### Coleta inicial de dados e criação do dicionário de dados
 - [x] Adicionou o conjunto de dados na pasta `data/raw/`?
 - [x] Criou e salvou o dicionário de dados na pasta `data/external/`?

### Exploração de dados
Pontos positivos
 - [x] Escreveu uma descrição dos dados?
 - [x] Falou sobre dados faltantes?
 - [x] Escreveu perguntas e partidas de hipóteses?
 - [x] Utilizou mais que 3 tipos de gráficos?
 - [x] Escreveu um sumário dos *insights* no final?
 - [x] Criou gráficos que não foram vistos em aula?
 - [x] Fez análise univariada?
 - [x] Fez análise bivariada?
 - [ ] Fez análise multivariada?

Pontos negativos
 - [ ] Usou canal de cor sem necessidade?
 - [ ] Utilizou rótulos inclinados?
 - [ ] Utilizou gráfico de dispersão quando deveria ter utilizado gráfico de boxplot?
 - [ ] Não ordenou gráficos de barra quando deveria?

 ---
 ### Comentários
 - Remover a primeira célula do notebook
 - Executar notebook todo novamente antes de fazer o commit
 - Boas perguntas de partida e hipóteses
 - Gráficos de barra:
   - Colocar valores nas barras
   - Se a variável é ordinal, os gráficos tem que seguir a ordem intrínseca das categorias
- Gráficos de distribuição das variáveis quantitativas:
  - Falar sobre a presença de outliers
- Gráfico de dispersão:
  - Remover contorno dos pontos, pois ele esconde os pontos quando a densidade é grande
  
---
cc @omadson
